server.port=5000

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://Jonathan:Ni9rmsCrWxswVkfv@cluster0.vh18rw6.mongodb.net/neobanco?appName=Cluster0
spring.data.mongodb.database=neobanco
spring.data.mongodb.auto-index-creation=false

# Optimización de Red: Compresión GZIP para agilizar las 16 peticiones del Dashboard
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
server.compression.min-response-size=1024

# JWT Configuration
jwt.secret=916c95bb72f951e59a23d8497024b32e4aa025b49ed0aee241fb0b3fec138c52e78b7dc7a75e70c222673e84d79cbaec430a116fa38d01372d6820a315905fce
jwt.expiration=2592000000

# CORS
cors.allowed-origins=http://localhost:5173


# ==========================================
# CONFIGURACION DE CORREO (GMAIL SMTP)
# ==========================================# Configuración de Correo SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=jonathangran471@gmail.com
spring.mail.password=psbbrdnxsavkkayv

# Propiedades avanzadas para JavaMail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtps.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.localhost=127.0.0.1
